<br /><br />
<div class="dashboardBody">
    Alumnos: <br />
    
    <b>GetAll</b>
    <dl>
        <?php foreach ($this->entries as $entry): ?>
            <dt><b>id de Alumno:</b> <?php echo $entry->getCodAlumno() ?></dt>
            <dd><b>Estado:</b> <?php echo $entry->getEstado() ?></dd>
            <dd><b>Correo:</b> <?php echo $entry->getCorreo() ?></dd>
            <dd><b>id de Usuario:</b> <?php echo $entry->getUsuarioCodUsuario() ?></dd>
            <dd><b>id de Datos Personales:</b> <?php echo $entry->getDatosPersonalesCodPersonal() ?></dd>
        <?php endforeach; ?>
    </dl>
    
    <b>GetOne</b>
    <dl>
        <dt><b>id de Alumno:</b> <?php echo $this->entries2->getCodAlumno() ?></dt>
        <dd><b>Estado:</b> <?php echo $this->entries2->getEstado() ?></dd>
        <dd><b>Correo:</b> <?php echo $this->entries2->getCorreo() ?></dd>
        <dd><b>id de Usuario:</b> <?php echo $this->entries2->getUsuarioCodUsuario() ?></dd>
        <dd><b>id de Datos Personales:</b> <?php echo $this->entries2->getDatosPersonalesCodPersonal() ?></dd>
    </dl>
</div>